djangonautic/accounts/urls.py
from django.urls import path
from . import views

app_name='accounts'

urlpatterns = [
    path('signup/', views.signup_view, name='signup' ),
    path('login/', views.login_view, name='login' ),
    path('logout/', views.logout_view, name='logout' ),
]

djangonautic/articles/urls.py
from django.urls import path
from . import views

app_name='articles'

urlpatterns = [
    path('', views.articles_list, name='articles_list' ),
    path('new/', views.new_article, name='new_article' ),
    path('<slug:slug>/', views.article_details, name='article_details')
]

djangonautic/djangonautic/urls.py
from django.conf.urls.static import static
from django.urls.conf import include
from django.contrib import admin
from django.conf import settings
from django.urls import path
from . import views
from articles import views as articles_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', articles_views.articles_list, name='home' ),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('about/', views.about )
]

urlpatterns += static(settings.STATIC_URL)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

djangonautic/accounts/models.py
from django.db import models

# Create your models here.

djangonautic/articles/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png', blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[0:50] + '...'

djangonautic/articles/forms.py
from django import forms
from . import models

class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title', 'slug', 'body', 'thumb']

djangonautic/accounts/views.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.shortcuts import redirect, render
from django.contrib.auth import login, logout

# Create your views here.
def signup_view(request): 
    if request.method == 'GET':
        form = UserCreationForm()
        return render(request, 'accounts/signup.html', {'form': form })
    else:
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('articles:articles_list')
        else:
            return render(request, 'accounts/signup.html', {'form': form })

def login_view(request): 
    if request.method == 'GET':
        form = AuthenticationForm()
        return render(request, 'accounts/login.html', {'form': form })

    else:
        form = AuthenticationForm(data = request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            next_url = request.POST.get('next')
            if next_url:
                return redirect(next_url)
            else:
                return redirect('articles:articles_list')
        else:
            return render(request, 'accounts/login.html', {'form': form })

def logout_view(request):
    if request.method == 'POST':
       logout(request)
       return redirect('articles:articles_list')

djangonautic/articles/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from .models import Article
from . import forms

def articles_list(request): 
    articles_list = Article.objects.all().order_by('date')
    return render(request, 'articles/articles_list.html', {'articles_list': articles_list})

def article_details(request, slug): 
    article = Article.objects.get(slug=slug)
    return render(request, 'articles/article_details.html', { 'article': article })

@login_required(login_url='accounts:login')
def new_article(request):
    if request.method == 'GET':
        form = forms.CreateArticle()
        return render(request, 'articles/new_article.html', {'form': form })

    else:
        form = forms.CreateArticle(request.POST)
        if form.is_valid():
            # Save form into DB
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()

            # Redirect
            return redirect('articles:articles_list')

djangonautic/djangonautic/views.py
from django.shortcuts import render

def homepage(request): 
    return render(request, 'homepage.html')

def about(request):
    return render(request, 'about.html')

djangonautic/accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Log in</h1>
    <form class='site-form' action="{% url 'accounts:login' %}" method="post">
        {% csrf_token %}
        {% if request.GET.next %}
            <input type="hidden" name="next" value='{{ request.GET.next }}'>
        {% endif %}
        {{ form }}
        <input type="submit" value="Log in">
    </form>
{% endblock %}

djangonautic/accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>SignUp</h1>
    <form class='site-form' action="/accounts/signup/" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Signup">
    </form>
{% endblock %}

djangonautic/articles/templates/articles/article_details.html
{% extends 'base_layout.html' %}

{% block content %} 
    <h1>Article Details</h1> 
    <div class='article-detail'>
        <div class='article'>
            <img src="{{ article.thumb.url }}">
            <h2>{{ article.title }}</h2>
            <p>{{ article.body }}</p>
            <p>{{ article.date }}</p>
        </div>
    </div>

{% endblock %}

djangonautic/articles/templates/articles/articles_list.html
{% extends 'base_layout.html' %}

{% block content %}

    <h1>Articles List</h1>
    <div class='articles'>
        {% for article in articles_list %}
            <div class="article">
                <h2><a href="{% url 'articles:article_details' slug=article.slug %}">{{ article.title }} </a></h2>
                <p>{{ article.snippet }} </p>
                <p>{{ article.date }} </p>
                <p class='author'>Added by: {{ article.author }}</p>
            </div>
        {% endfor %}
    </div>

{% endblock %}

djangonautic/articles/templates/articles/new_article.html
{% extends 'base_layout.html' %}

{% block content %}

    <div class="create-article">
        <form class="site-form" action="{% url 'articles:new_article' %}" method="post" enctype='multipart/form-data'>
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Create">
        </form>
    </div>

{% endblock %}

djangonautic/templates/about.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>About us</h1>
    <p>We like Django</p>
{% endblock %}

djangonautic/templates/base_layout.html
{% load static %}
<!DOCTYPE html> 
<html lang="en"> 
    <head> 
        <meta charset="UTF-8"> 
        <meta http-equiv="X-UA-Compatible" content="IE=edge"> 
        <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
        <link rel="stylesheet" href="{% static 'styles.css' %}">
        <title>Djangonautic</title> 
    </head>

    <body> 
        <header class='wrapper'>
            <h1><a href="{% url 'home' %}"><img src="{% static 'logo.png' %}" alt="djangonautic" /></a></h1>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                        <li>
                            <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                                {% csrf_token %}
                                <button type="submit">Logout</button>
                            </form>
                        </li>
                        <li><a class='highlight' href="{% url 'articles:new_article' %}">New Article</a></li>
                    {% else %}
                        <li><a href="{% url 'accounts:signup' %}">Sign Up</a></li>
                        <li><a href="{% url 'accounts:login' %}">Login</a></li>
                    {% endif %}
                </ul>
            </nav>
        </header> 
        <div class="wrapper">
            {% block content %}
            {% endblock %}
        </div>
    </body> 
</html>

djangonautic/templates/homepage.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>This is the homepage</h1>
    <p>Welcome to Djangonautic</p>
{% endblock %}